"""create learning and payment tables

Revision ID: ec0337f01d19
Revises: 82300566a926
Create Date: 2026-09-24 20:17:48.291232

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec0337f01d19"
down_revision: Union[str, Sequence[str], None] = "82300566a926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_categories_slug"),
    )
    op.create_table(
        "instructors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("headline", sa.String(length=100), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "expired", "canceled", name="order_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total_price >= 0", name="chk_orders_total_price"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number", name="uq_orders_order_number"),
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "courses",
        sa.Column("instructor_id", sa.Uuid(), nullable=False),
        sa.Column("instructor_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail", sa.String(length=255), nullable=False),
        sa.Column(
            "level",
            sa.Enum("beginner", "intermediate", "advanced", "all_level", name="level"),
            server_default="all_level",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="course_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("enrollment_count", sa.Integer(), nullable=False),
        sa.Column("total_duration_mins", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "avg_rating >= 0 AND avg_rating <= 5", name="chk_courses_avg_rating"
        ),
        sa.CheckConstraint(
            "enrollment_count >= 0", name="chk_courses_enrollment_count"
        ),
        sa.CheckConstraint("price >= 0", name="chk_courses_price"),
        sa.CheckConstraint("rating_count >= 0", name="chk_courses_rating_count"),
        sa.CheckConstraint(
            "total_duration_mins >= 0", name="chk_courses_total_duration_mins"
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_courses_slug"),
    )
    op.create_index(
        op.f("ix_courses_instructor_id"), "courses", ["instructor_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("stripe", "paypal", "zalopay", name="provider"),
            nullable=False,
        ),
        sa.Column("merchant_reference", sa.String(length=255), nullable=False),
        sa.Column("provider_checkout_id", sa.String(length=255), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "pending",
                "processing",
                "succeeded",
                "failed",
                "canceled",
                "expired",
                name="payment_status",
            ),
            server_default="created",
            nullable=False,
        ),
        sa.Column("provider_status", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("failure_code", sa.String(length=50), nullable=True),
        sa.Column("failure_message", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount >= 0", name="chk_payments_amount"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "merchant_reference", name="uq_payments_merchant_reference"
        ),
        sa.UniqueConstraint(
            "provider",
            "provider_checkout_id",
            name="uq_payments_provider_provider_checkout_id",
        ),
        sa.UniqueConstraint(
            "provider",
            "provider_payment_id",
            name="uq_payments_provider_provider_payment_id",
        ),
    )
    op.create_index(
        op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False
    )
    op.create_table(
        "chapters",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('"order" >= 1', name="chk_chapters_order"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "order", name="uq_chapters_course_order"),
    )
    op.create_table(
        "course_categories",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "category_id"),
    )
    op.create_index(
        op.f("ix_course_categories_category_id"),
        "course_categories",
        ["category_id"],
        unique=False,
    )
    op.create_table(
        "enrollments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", name="enrollment_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("completed_at > enrolled_at", name="chk_completed_enrolled"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollments_user_course"),
    )
    op.create_index(
        op.f("ix_enrollments_course_id"), "enrollments", ["course_id"], unique=False
    )
    op.create_table(
        "order_details",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0", name="chk_order_details_price"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "course_id", name="uq_order_details_order_course"
        ),
    )
    op.create_table(
        "reviews",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="chk_reviews_rating"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "user_id", name="uq_reviews_user_course"),
    )
    op.create_table(
        "exercises",
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="exercise_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("time_limit_mins", sa.Integer(), nullable=True),
        sa.Column(
            "pass_score_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("max_attempts >= 1", name="chk_exercises_max_attempts"),
        sa.CheckConstraint('"order" >= 1', name="chk_exercises_order"),
        sa.CheckConstraint(
            "pass_score_percent >= 0 AND pass_score_percent <= 100",
            name="chk_exercises_pass_score_percent",
        ),
        sa.CheckConstraint(
            "time_limit_mins >= 1", name="chk_exercises_time_limit_mins"
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "order", name="uq_exercises_chapter_order"),
    )
    op.create_table(
        "lessons",
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("video", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "ready", "failed", name="lesson_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("duration_secs", sa.Integer(), nullable=True),
        sa.Column("is_preview", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_secs > 0", name="chk_lessons_duration_secs"),
        sa.CheckConstraint('"order" >= 1', name="chk_lessons_order"),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chapter_id", "order", name="uq_lessons_chapter_order"),
    )
    op.create_table(
        "exercise_attempts",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress", "submitted", "graded", name="exercise_attempt_status"
            ),
            server_default="in_progress",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "pass_score_percent", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_number >= 1", name="chk_exercise_attempts_attempt_number"
        ),
        sa.CheckConstraint(
            "pass_score_percent >= 0 AND pass_score_percent <= 100",
            name="chk_exercise_attempts_pass_score_percent",
        ),
        sa.CheckConstraint("score >= 0", name="chk_exercise_attempts_score"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exercise_id",
            "user_id",
            "attempt_number",
            name="uq_exercise_attempts_user_exercise",
        ),
    )
    op.create_table(
        "lesson_progresses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("last_watched_secs", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "last_watched_secs >= 0", name="chk_lesson_progresses_watched_secs"
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_id"),
    )
    op.create_table(
        "questions",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("single_choice", "multiple_choice", "essay", name="type"),
            server_default="single_choice",
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("points", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('"order" >= 1', name="chk_questions_order"),
        sa.CheckConstraint("points >= 0", name="chk_questions_points"),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exercise_id", "order", name="uq_questions_exercise_order"),
    )
    op.create_table(
        "choices",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('"order" >= 1', name="chk_choices_order"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "order", name="uq_choices_question_order"),
    )
    op.create_table(
        "question_answers",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("earned_point", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("graded_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exercise_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graded_by"],
            ["instructors.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name="uq_question_answers_attempt_question"
        ),
    )
    op.create_table(
        "answer_choices",
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("choice_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["question_answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["choice_id"],
            ["choices.id"],
        ),
        sa.PrimaryKeyConstraint("answer_id", "choice_id"),
    )
    if not any(
        col["name"] == "updated_at"
        for col in sa.inspect(op.get_bind()).get_columns("users")
    ):
        op.add_column(
            "users",
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )

    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_table("answer_choices")
    op.drop_table("question_answers")
    op.drop_table("choices")
    op.drop_table("questions")
    op.drop_table("lesson_progresses")
    op.drop_table("exercise_attempts")
    op.drop_table("lessons")
    op.drop_table("exercises")
    op.drop_table("reviews")
    op.drop_table("order_details")
    op.drop_index(op.f("ix_enrollments_course_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(
        op.f("ix_course_categories_category_id"), table_name="course_categories"
    )
    op.drop_table("course_categories")
    op.drop_table("chapters")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_courses_instructor_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("instructors")
    op.drop_table("categories")
    # ### end Alembic commands ###
